export const spells = [ "Charm Person",
"Detect Magic",
"Floating Disc",
"Hold Portal",
"Light (Darkness)",
"Magic Missile",
"Protection from Evil",
"Read Languages",
// "Read Magic",
"Shield",
"Sleep",
"Ventriloquism"];